### ISSUE TITLE
Import swipl-web.wasm and swipl-web.data relative to `swipl-web.js` rather than the global script.

### ISSUE THREAD

**Issue by jeswr** [SWI-Prolog/swipl-devel#1027]
Related to #1024

Otherwise, if I have the folder structure
 - script.js
 - swipl/
   - swipl-web.data
   - swipl-web.js
   - swipl-web.wasm
   - index.js
   
 With 
 
 index.js
 ```js
export default async function SWIPL(module) {
  await require('./swipl-web.js')(module);
}

 ```
   
 script.js
 ```js
 import SWIPL from './swipl';
async function createSWIPLModule(options: SwiplOptions = {}): Promise<SwiplModule> {
  const Module = {
    noInitialRun: true,
    arguments: [],
    locateFile: (file: string) => `./${file}`,
    print: (str: string) => {},
    printErr: (line: any) => {},
    ...options,
  } as any;
  await SWIPL(Module);
  return Module
}

createSWIPLModule()
 ```
 
 Then I get the error
 
 ```
[jeswr@orangejuly lib]$ node script.js 
/home/jeswr/Documents/rdfstar/eye.js/lib/swipl/swipl-web.js:1132
                        throw ex
                        ^

RuntimeError: Aborted(Error: ENOENT: no such file or directory, open 'swipl-web.wasm'). Build with -sASSERTIONS for more info.
    at abort (/home/jeswr/Documents/rdfstar/eye.js/lib/swipl/swipl-web.js:1436:25)
    at getBinary (/home/jeswr/Documents/rdfstar/eye.js/lib/swipl/swipl-web.js:1465:21)
    at /home/jeswr/Documents/rdfstar/eye.js/lib/swipl/swipl-web.js:1493:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.4.0
 ```

**Comment by jan-swi-prolog-01** [comment]
AFAIK this is all generated code by Emscripten, so there is little we can do.   Of course, I could be wrong.  I'm a Prolog and C programmer.

**Comment by jeswr** [comment]
This would indicate it should be possible https://web.dev/emscripten-npm/. I'm guessing the current issue would be that [here](https://github.com/josd/eyebrow/blob/3b9d4d8dea4b9c929383060f763af881717c44ba/swipl-web.js#L1456) `locateFile` is not doing the relative loading I will expect.

I haven't had the chance to dig in deep enough to see if there are any bugs the emscripten team would need to resolve or if a bundler can do what is needed.

**Comment by Jean-Luc-Picard-2021** [comment]
Inside swipl.js, you could call `document.currentScript.src` at
load time, and use this as a base. I have just added a new Prolog
flag `system_url` to Dogelog Player that just does that:
```
let bootbase;
if (fs !== undefined) {
    bootbase = require.main.filename;
} else {
    bootbase = document.currentScript.src;
}
```
If the script is run as a module you possibly need to use
something else than document.currentScript.src .
SWIPL WASM then becomes completely relocatable. To use

a base url and resolve some other url, you can use the
JavaScript class URL and this programming idiom:
```
url = new URL(url, base).href
```
Otherwise, if you don't do something like this, I guess
fetches and XMLHttpRequests are resolved by the current
main document URL or frame URL, in the HTML pages

a base URL automatically provided by the browser when
you do relative fetches or XMLHttpRequests.

**Comment by rla** [comment]
With that directory structure you likely want locateFile: (file: string) => `./swipl/${file}` in the module options.

**Comment by Jean-Luc-Picard-2021** [comment]
How do you put a devel and a stable version side by side on the same server?

Like for example:
```
<webcontext>/stable/lib/swipl.js
<webcontext>/stable/appfolder/index.html      /* with loads script .../swipl.js */
<webcontext>/devel/lib/swipl.js
<webcontext>/devel/appfolder/index.html      /* with loads script .../swipl.js */
```

**Comment by rla** [comment]
> How do you put a devel and a stable version side by side on the same server?

locateFile can return host-relative absolute path like /devel/lib/swipl.data for this use case.

**Comment by Jean-Luc-Picard-2021** [comment]
How do you make a locateFile that you never need to rewrite?

**Comment by rla** [comment]
> The problem I am trying to adress is rather, how do you make a locateFile that you almost never need to rewrite?

Since you define it in your own script, example:
https://github.com/SWI-Prolog/swipl-devel/blob/master/src/wasm/test.html#L26

You can make it conditional wrt current URL (check if window.location contains stable/devel/etc).

**Comment by Jean-Luc-Picard-2021** [comment]
Self orienting means, that the test.html doesn't need to put
an absolute address, it could also put a relative address or a CDN adress:
So instead:
```
<script src="/wasm/swipl-web.js"></script>
```
It could be a tar ball with WASM, self contained:
```
<script src="../lib/swipl-web.js"></script>
```
Or with a CDN refernce:
```
<script src="<cdn>/version/swipl-web.js"></script>
```

**Comment by rla** [comment]
> Self orienting means

What if you leave it empty? By docs it might try to find the files from the right location then: https://emscripten.org/docs/api_reference/module.html#Module.locateFile

**Comment by Jean-Luc-Picard-2021** [comment]
I dont know, does it work?

**Comment by rla** [comment]
> (top of thread)

The top of thread has this issue when running in Node.js with ES modules. Node.js uses different file/module resolution than browsers. Different approaches are necessary but they should be achivable with returning approriate path from locateFile. Node.js CommonJS modules always have __dirname (https://nodejs.org/api/modules.html#__dirname), in ES setting you would need to use something else (https://blog.logrocket.com/alternatives-dirname-node-js-es-modules/), and in browser you can use window.location to get the current file/path and then rewrite actual locations against it.

**Comment by JanWielemaker** [comment]
The WASM interface is now pretty stable and this seems obsolete.   Closing.
