### ISSUE TITLE
Order of PL_new_*() functions before PL_initialise() can cause crash

### ISSUE THREAD

**Issue by kamahen** [SWI-Prolog/swipl-devel#1155]
It's not clear how  to reproduce this problem; the following sequence (using the C++ API) seems to cause the problem (when `PL_set_prolog_flag()` is called), but only when used with packages/swipl-win -- a short program with just this worked fine:
```
#include "SWI-cpp2.cpp" // This could be a separate file that's compiled by itself.
static PlFunctor xFUNCTOR_error_2("error", 2);
static PlFunctor xFUNCTOR_resource_error_1("resource_error", 1);
int main() {
  PL_set_prolog_flag("console_menu", PL_BOOL|FF_READONLY, TRUE);
  return  0;
}
```
The traceback appears to be a wild branch:
```
$ gdb /home/peter/src/swipl-devel/build.debug/packages/swipl-win/swipl-win
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
   ...
Reading symbols from /home/peter/src/swipl-devel/build.debug/packages/swipl-win/swipl-win...
(gdb) run
Starting program: /home/peter/src/swipl-devel/build.debug/packages/swipl-win/swipl-win
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
***PlExitDebug WRAP-new_atom_nchars
***PlExitDebug WRAP-new_functor
***PlExitDebug VOID-unregister_atom
***PlExitDebug WRAP-new_atom_nchars
***PlExitDebug WRAP-new_functor
***PlExitDebug VOID-unregister_atom
[New Thread 0x7ffff2a67700 (LWP 2940)]
[New Thread 0x7ffff0b8b700 (LWP 2941)]
[New Thread 0x7fffebfff700 (LWP 2942)]

Thread 4 "SwiPrologEngine" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffebfff700 (LWP 2942)]
0x00007ffff7e93611 in MurmurHashAligned2 (key=0x5555555a8750, len=12, seed=440132426) at ../src/pl-hash.c:72
72  DEBUG(0, assert(sizeof(int) == 4));
(gdb) bt
#0  0x00007ffff7e93611 in MurmurHashAligned2 (key=0x5555555a8750, len=12, seed=440132426)
    at ../src/pl-hash.c:72
#1  0x00007ffff7d4b4a9 in lookupBlob
    (s=0x5555555a8750 "console_menu", length=12, type=0x7ffff7fc03a0 <text_atom>, new=0x7fffebffe9cc)
    at ../src/pl-atom.c:544
#2  0x00007ffff7d4be72 in lookupAtom (s=0x5555555a8750 "console_menu", length=12) at ../src/pl-atom.c:662
#3  0x00007ffff7ef1386 in PL_new_atom (s=0x5555555a8750 "console_menu") at ../src/pl-fli.c:572
#4  0x00007ffff7f37868 in setPrologFlag (name=0x5555555a8750 "console_menu", flags=4097)
    at ../src/os/pl-prologflag.c:143
#5  0x00007ffff7efd330 in PL_set_prolog_flag (name=0x5555555a8750 "console_menu", type=4113)
    at ../src/pl-fli.c:5161
#6  0x0000555555580070 in SwiPrologEngine::run() (this=0x555555ce34a0)
    at ../packages/swipl-win/SwiPrologEngine.cpp:227
#7  0x00007ffff6b40be1 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff6425ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007ffff6755a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```

**Comment by JanWielemaker** [comment]
Seems a mystery from C++ global initialization.   Can be avoided by using static atoms and functors inside a function.   Closing.
