### ISSUE TITLE
Segmentation fault in call to get_rational_no_int

### ISSUE THREAD

**Issue by etrian-dev** [SWI-Prolog/swipl-devel#1254]
Hi again,

thanks for the quick response on the previous issue (#1253).
I'm using swipl as a build dependency for another software. I recently upgraded from version 8.5.13 to 9.3.3 on a Linux machine (Ubuntu 22.04).
I use swipl with gmp support (gmp 6.2.1).
I'm using the foreign language interface to call into swipl from C++. I observed a segmentation fault inside a call to PL_get_mpq. See below for more details:

```Thread 1 "eclair" hit Breakpoint 1, PL_get_mpq (t=1310, mpq=0x7fffffff3300) at /home/nicola/eclair/develop/deps/build/swipl-9.3.3/src/pl-gmp.c:2123
2123	{ if ( PL_is_rational(t) )
(gdb) s
PL_is_rational (t=1310) at /home/nicola/eclair/develop/deps/build/swipl-9.3.3/src/pl-fli.c:2434
2434	{ GET_LD
(gdb) n
2435	  word w = valHandle(t);
(gdb) n
2437	  return isRational(w);
(gdb) p w
$1 = 24687883
(gdb) p/x w
$2 = 0x178b50b
(gdb) s
2438	}
(gdb) s
PL_get_mpq (t=1310, mpq=0x7fffffff3300) at /home/nicola/eclair/develop/deps/build/swipl-9.3.3/src/pl-gmp.c:2123
2123	{ if ( PL_is_rational(t) )
(gdb) s
2124	  { GET_LD
(gdb) s
2127	    get_rational(t, &n);
(gdb) s
get_rational___LD (__PL_ld=0x7ffff7ecc120 <PL_local_data>, w=1310, n=0x7fffffff3210) at /home/nicola/eclair/develop/deps/build/swipl-9.3.3/src/pl-gmp.h:177
177	{ if ( storage(w) == STG_INLINE )
(gdb) n
181	  { get_rational_no_int(w, n);
(gdb) s
get_rational_no_int___LD (__PL_ld=0x7ffff7ecc120 <PL_local_data>, w=1310, n=0x7fffffff3210) at /home/nicola/eclair/develop/deps/build/swipl-9.3.3/src/pl-gmp.c:498
498	{ Word p = addressIndirect(w);
(gdb) p w
$3 = 1310
(gdb) p/x w
$4 = 0x51e
(gdb) s
499	  size_t wsize = wsizeofInd(*p);
(gdb) p p
$5 = (Word) 0x28
(gdb) ptype p
type = unsigned long *
(gdb) s

Thread 1 "eclair" received signal SIGSEGV, Segmentation fault.
0x00007ffff7d82076 in get_rational_no_int___LD (__PL_ld=0x7ffff7ecc120 <PL_local_data>, w=1310, n=0x7fffffff3210) at /home/nicola/eclair/develop/deps/build/swipl-9.3.3/src/pl-gmp.c:499
499	  size_t wsize = wsizeofInd(*p);
```

One observation that may or may not be relevant is that ```PL_is_rational(t)``` is called and returns a truthy value without issues, while ```get_rational``` called with the same argument ```t``` leads to a crash.
Here's the backtrace:

```
(gdb) bt
#0  0x00007ffff7d82076 in get_rational_no_int___LD (__PL_ld=0x7ffff7ecc120 <PL_local_data>, w=1310, n=0x7fffffff3210) at /home/nicola/eclair/develop/deps/build/swipl-9.3.3/src/pl-gmp.c:499
#1  0x00007ffff7d7f97f in get_rational___LD (__PL_ld=0x7ffff7ecc120 <PL_local_data>, w=1310, n=0x7fffffff3210) at /home/nicola/eclair/develop/deps/build/swipl-9.3.3/src/pl-gmp.h:181
#2  0x00007ffff7d85e76 in PL_get_mpq (t=1310, mpq=0x7fffffff3300) at /home/nicola/eclair/develop/deps/build/swipl-9.3.3/src/pl-gmp.c:2127
#3  0x00005555562fdf01 in Prolog_get_mpq_t (t=0x51e, q=0x7fffffff3300) at /home/nicola/eclair/eclair/common/pcfli/swi_cfli.inlines.h:946
#4  0x00005555562fe161 in ECLAIR::Prolog_Converter::get (q=..., tTerm=0x51e) at /home/nicola/eclair/eclair/c/parser/Prolog_Converter.inlines.hh:280
#5  0x000055555654ea3c in parser_approximate_to_floating (tFrom=0x51e, type=0x555561ca0140, tRounding=0x520, tState=@0x7fffffff33d0: 0x100000008, tRel=@0x7fffffff33d8: 0x531, tTo=@0x7fffffff33e0: 0x52a)
    at /home/nicola/eclair/eclair/c/parser/Prolog_interface_parser.cc:3030
#6  0x00005555565ddf75 in call_function<Prolog_term_ref_*, clang::BuiltinType*, Prolog_term_ref_*, Prolog_term_ref_*, Prolog_term_ref_*, Prolog_term_ref_*, int, int, int, int, int, int> (
    function=0x55555654e6f5 <parser_approximate_to_floating(Prolog_term_ref_*, clang::BuiltinType*, Prolog_term_ref_*, Prolog_term_ref_*&, Prolog_term_ref_*&, Prolog_term_ref_*&)>, tArg1=0x51e, tArg2=0x51f, tArg3=0x520, 
    tArg4=0x521, tArg5=0x522, tArg6=0x523, p1=0, p2=0, p3=0, p4=0, p5=0, p6=0) at /home/nicola/eclair/eclair/c/parser/Prolog_interface_parser.cc:5718
#7  0x00005555565ab1b6 in parser_approximate_to_floating6 (tArg1=0x51e, tArg2=0x51f, tArg3=0x520, tArg4=0x521, tArg5=0x522, tArg6=0x523) at /home/nicola/eclair/eclair/c/parser/foreigns.def:742
#8  0x00007ffff7c54293 in PL_next_solution___LD (__PL_ld=0x7ffff7ecc120 <PL_local_data>, qid=0x555561cc4090) at /home/nicola/eclair/develop/deps/build/swipl-9.3.3/src/pl-vmi.c:4699
#9  0x00007ffff7df4fcb in PL_call_predicate (ctx=0x0, flags=2, pred=0x55555f3540f0, h0=353) at /home/nicola/eclair/develop/deps/build/swipl-9.3.3/src/pl-fli.c:4281
#10 0x0000555555ed72de in (anonymous namespace)::call_prolog (tGoal=0x161) at /home/nicola/eclair/eclair/c/main.cc:184
#11 0x0000555555eda1c6 in ECLAIR::F_compiler::eval (this=0x55555bdccae0 <ECLAIR::f_compiler>, tool_exe=..., tool_cmd=..., tool_args=..., tool_args_string=...) at /home/nicola/eclair/eclair/c/main.cc:810
#12 0x0000555555edc99f in ECLAIR::Function::operator() (this=0x55555bdccae0 <ECLAIR::f_compiler>, a0=..., a1=..., a2=..., a3=..., pos=...) at /home/nicola/eclair/eclair/common/cutils/functions.inlines.hh:721
#13 0x0000555555ee4fea in ECLAIR::Function_A<ECLAIR::Cell_String, ECLAIR::Cell_String, ECLAIR::Cell_Is_List<ECLAIR::Cell_String, 0, -1>, ECLAIR::Cell_String, void, void>::apply (this=0x55555bdccae0 <ECLAIR::f_compiler>, args=..., 
    evaluate=true, pos=...) at /home/nicola/eclair/eclair/common/cutils/functions.inlines.hh:854
#14 0x00005555566b53b7 in ECLAIR::Environ::apply_ (this=0x55555bdc5880 <ECLAIR::env>, function=..., arguments=..., evaluate=true, pos=...) at /home/nicola/eclair/eclair/common/cutils/functions.cc:392
#15 0x00005555566b4c87 in ECLAIR::Environ::apply (this=0x55555bdc5880 <ECLAIR::env>, function=..., arguments=..., evaluate=true, pos=...) at /home/nicola/eclair/eclair/common/cutils/functions.cc:360
#16 0x00005555566b5977 in ECLAIR::Environ::eval (this=0x55555bdc5880 <ECLAIR::env>, expr=...) at /home/nicola/eclair/eclair/common/cutils/functions.cc:412
#17 0x00005555563883e9 in ECLAIR::Environ::eval_stream<ECLAIR::I_EFStream> (this=0x55555bdc5880 <ECLAIR::env>, is=..., pos=...) at /home/nicola/eclair/eclair/common/cutils/functions.templates.hh:645
```

there are more frames below, but they are deeper inside the calling code, so possibly of little interest.

**Comment by JanWielemaker** [comment]
wrong type, buts as they are both integers, the compiler does not complain.  There is no test case ...
